server :
  port : 8080
  
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    content-type: text/html;
    charset: UTF-8
    cache: false
    
    
