# Servlet, Spring Settings..
server:
  port: 8080
spring:
  application:
    name: hands-api-gateway

#zuul Settings
zuul:
  routes:
    hands-auth-service:
      path: /auth/**
      url: http://i4d101.p.ssafy.io:8081/
      sensitiveHeaders: Cookie,Set-Cookie
    hands-credit-service:
      path: /credit/**
      url: http://i4d101.p.ssafy.io:8082/
      sensitiveHeaders: Cookie,Set-Cookie
    hands-chat-service:
      path: /chat/**
      url: http://i4d101.p.ssafy.io:8050/
      sensitiveHeaders: Cookie,Set-Cookie
    hands-job-service:
      path: /job/**
      url: http://i4d101.p.ssafy.io:8051/Jobs
      sensitiveHeaders: Cookie,Set-Cookie
    hands-social-service:
      path: /social/**
      url: http://i4d101.p.ssafy.io:8052/
      sensitiveHeaders: Cookie,Set-Cookie
    hands-contract-service:
        path: /contract/**
        url: http://i4d101.p.ssafy.io:8053/
        sensitiveHeaders: Cookie,Set-Cookie
    hands-mail-auth-service:
      path: /mail/**
      url: http://i4d101.p.ssafy.io:8000/mail-auth
      sensitiveHeaders: Cookie,Set-Cookie
    hands-review-service:
      path: /review/**
      url: http://i4d101.p.ssafy.io:8001/review
      sensitiveHeaders: Cookie,Set-Cookie
    hands-keyword-service:
      path: /keyword/**
      url : http://i4d101.p.ssafy.io:8002/
      sensitiveHeaders: Cookie,Set-Cookie
# Eureka Client Settings
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i4d101.p.ssafy.io:8761/eureka
