server :
  port : 8052

  
spring:
  application:
    name: HANDS-FOLLOW-SERVICE
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  profiles:
    active: local
  redis:  
    host: i4d101.p.ssafy.io
    port: 6379
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i4d101.p.ssafy.io:8761/eureka